# fly.toml app configuration file generated for lhg on 2025-09-04T11:09:26+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lhg'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
